version: '3.8'

services:
  db:
    image: postgres:16
    container_name: paynes-postgres
    environment:
      POSTGRES_USER: paynesuser
      POSTGRES_PASSWORD: paynespass
      POSTGRES_DB: paynesdb
    ports:
      - "5432:5432"

  app:
    image: paynes-app
    container_name: paynes-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paynesdb
      SPRING_DATASOURCE_USERNAME: paynesuser
      SPRING_DATASOURCE_PASSWORD: paynespass
    depends_on:
      - db
